import {
    Type,
    Mail,
    Phone,
    AlignLeft,
    Calendar,
    CheckSquare,
    CircleDot,
    Hash,
    Upload,
    Link,
    Lock,
    Building2,
    Columns2,
    Columns3,
    Rows2,
    Save,
    Pencil,
    Eye,
    Plus,
} from "lucide-react";

export const LAYOUT_DATA = [
    {
        id: "grid-2",
        label: "2 Columns",
        type: "layout-grid",
        columns: 2,
        category: "layout",
        description: "Two equal columns side by side",
        icon: <Columns2 className="size-4" />,
    },
    {
        id: "grid-3",
        label: "3 Columns",
        type: "layout-grid",
        columns: 3,
        category: "layout",
        description: "Three equal columns side by side",
        icon: <Columns3 className="size-4" />,
    },
    {
        id: "row-group",
        label: "Row Group",
        type: "layout-row",
        columns: 1,
        category: "layout",
        description: "Group elements in a vertical row",
        icon: <Rows2 className="size-4" />,
    }
] as const;

export const FIELD_DATA = [
    {
        id: "name",
        label: "Full Name",
        htmlTag: "input",
        inputType: "text",
        placeholder: "Enter your full name",
        isRequired: true,
        name: "fullName",
        category: "smart",
        description: "Take the user's full name",
        icon: <Type className="size-4" />,
    },
    {
        id: "email",
        label: "Email",
        htmlTag: "input",
        inputType: "email",
        placeholder: "Enter your email",
        isRequired: true,
        name: "email",
        category: "smart",
        description: "Collect email address",
        icon: <Mail className="size-4" />,
    },
    {
        id: "phone",
        label: "Phone Number",
        htmlTag: "input",
        inputType: "tel",
        placeholder: "Enter your phone number",
        isRequired: true,
        name: "phone",
        category: "smart",
        description: "Collect phone number",
        icon: <Phone className="size-4" />,
    },
    {
        id: "password",
        label: "Password",
        htmlTag: "input",
        inputType: "password",
        placeholder: "Enter your password",
        isRequired: true,
        name: "password",
        category: "smart",
        description: "Password input field",
        icon: <Lock className="size-4" />,
    },
    {
        id: "website",
        label: "Website",
        htmlTag: "input",
        inputType: "url",
        placeholder: "https://example.com",
        isRequired: false,
        name: "website",
        category: "smart",
        description: "Collect website URL",
        icon: <Link className="size-4" />,
    },
    {
        id: "company",
        label: "Company",
        htmlTag: "input",
        inputType: "text",
        placeholder: "Enter company name",
        isRequired: false,
        name: "company",
        category: "smart",
        description: "Collect company name",
        icon: <Building2 className="size-4" />,
    },
    {
        id: "text",
        label: "Text Input",
        htmlTag: "input",
        inputType: "text",
        placeholder: "Enter text",
        isRequired: false,
        name: "textInput",
        category: "basic",
        description: "Single line text input",
        icon: <Type className="size-4" />,
    },
    {
        id: "number",
        label: "Number",
        htmlTag: "input",
        inputType: "number",
        placeholder: "Enter a number",
        isRequired: false,
        name: "number",
        category: "basic",
        description: "Numeric input",
        icon: <Hash className="size-4" />,
    },
    {
        id: "textarea",
        label: "Textarea",
        htmlTag: "textarea",
        placeholder: "Enter your message",
        isRequired: false,
        name: "message",
        category: "basic",
        description: "Multi-line text input",
        icon: <AlignLeft className="size-4" />,
    },
    {
        id: "date",
        label: "Date",
        htmlTag: "input",
        inputType: "date",
        isRequired: false,
        name: "date",
        category: "basic",
        description: "Pick a date",
        icon: <Calendar className="size-4" />,
    },
    {
        id: "file",
        label: "File Upload",
        htmlTag: "input",
        inputType: "file",
        isRequired: false,
        name: "file",
        category: "basic",
        description: "Upload files",
        icon: <Upload className="size-4" />,
    },
    {
        id: "checkbox",
        label: "Checkbox",
        htmlTag: "checkbox",
        isRequired: false,
        name: "checkbox",
        category: "choice",
        description: "Single checkbox",
        icon: <CheckSquare className="size-4" />,
    },
    {
        id: "radio",
        label: "Radio Group",
        htmlTag: "radio-group",
        isRequired: false,
        name: "radioGroup",
        category: "choice",
        description: "Choose one option",
        icon: <CircleDot className="size-4" />,
        options: [
            { label: "Yes", value: "yes" },
            { label: "No", value: "no" },
        ],
    },
] as const;



// header buttons
import { TabOption } from "./form-tools/HeaderTab";

export const LAYOUT_BUTTON_TABS: TabOption<"elements" | "layouts">[] = [
    { id: "layouts", label: "Layout", icon: <Pencil className="size-3.5" /> },
    { id: "elements", label: "Form Elements", icon: <Plus className="size-3.5" /> }
]

export const VIEW_MODE_BUTTON_TABS: TabOption<"edit" | "preview">[] = [
    { id: "edit", label: "Edit", icon: <Pencil className="size-3.5" /> },
    { id: "preview", label: "Preview", icon: <Eye className="size-3.5" /> }
]
