import {
    Type,
    Mail,
    Phone,
    AlignLeft,
    Calendar,
    CheckSquare,
    CircleDot,
    Hash,
    Upload,
    Link,
    Lock,
    Building2,
} from "lucide-react";
import type { FieldDefinition } from "../types";

export const FIELD_DATA: FieldDefinition[] = [
    {
        id: "name",
        label: "Full Name",
        category: "smart",
        description: "Take the user's full name",
        icon: <Type className="size-4" />,
        defaultProps: {
            label: "Full Name",
            isRequired: true,
            placeholder: "Enter your full name",
            inputType: "text",
        },
    },
    {
        id: "email",
        label: "Email",
        category: "smart",
        description: "Collect email address",
        icon: <Mail className="size-4" />,
        defaultProps: {
            label: "Email",
            isRequired: true,
            placeholder: "Enter your email",
            inputType: "email",
        },
    },
    {
        id: "phone",
        label: "Phone Number",
        category: "smart",
        description: "Collect phone number",
        icon: <Phone className="size-4" />,
        defaultProps: {
            label: "Phone Number",
            isRequired: true,
            placeholder: "Enter your phone number",
            inputType: "tel",
        },
    },
    {
        id: "password",
        label: "Password",
        category: "smart",
        description: "Password input field",
        icon: <Lock className="size-4" />,
        defaultProps: {
            label: "Password",
            isRequired: true,
            placeholder: "Enter your password",
            inputType: "password",
        },
    },
    {
        id: "website",
        label: "Website",
        category: "smart",
        description: "Collect website URL",
        icon: <Link className="size-4" />,
        defaultProps: {
            label: "Website",
            isRequired: false,
            placeholder: "https://example.com",
            inputType: "url",
        },
    },
    {
        id: "company",
        label: "Company",
        category: "smart",
        description: "Collect company name",
        icon: <Building2 className="size-4" />,
        defaultProps: {
            label: "Company",
            isRequired: false,
            placeholder: "Enter company name",
            inputType: "text",
        },
    },
    {
        id: "text",
        label: "Text Input",
        category: "basic",
        description: "Single line text input",
        icon: <Type className="size-4" />,
        defaultProps: {
            label: "Text Input",
            isRequired: false,
            placeholder: "Enter text",
            inputType: "text",
        },
    },
    {
        id: "number",
        label: "Number",
        category: "basic",
        description: "Numeric input",
        icon: <Hash className="size-4" />,
        defaultProps: {
            label: "Number",
            isRequired: false,
            placeholder: "Enter a number",
            inputType: "number",
        },
    },
    {
        id: "textarea",
        label: "Textarea",
        category: "basic",
        description: "Multi-line text input",
        icon: <AlignLeft className="size-4" />,
        defaultProps: {
            label: "Textarea",
            isRequired: false,
            placeholder: "Enter your message",
        },
    },
    {
        id: "date",
        label: "Date",
        category: "basic",
        description: "Pick a date",
        icon: <Calendar className="size-4" />,
        defaultProps: {
            label: "Date",
            isRequired: false,
            inputType: "date",
        },
    },
    {
        id: "file",
        label: "File Upload",
        category: "basic",
        description: "Upload files",
        icon: <Upload className="size-4" />,
        defaultProps: {
            label: "File Upload",
            isRequired: false,
        },
    },
    {
        id: "checkbox",
        label: "Checkbox",
        category: "choice",
        description: "Single checkbox",
        icon: <CheckSquare className="size-4" />,
        defaultProps: {
            label: "Checkbox",
            isRequired: false,
        },
    },
    {
        id: "radio",
        label: "Radio Group",
        category: "choice",
        description: "Choose one option",
        icon: <CircleDot className="size-4" />,
        defaultProps: {
            label: "Radio Group",
            isRequired: false,
            options: [
                { label: "Yes", value: "yes" },
                { label: "No", value: "no" },
            ],
        },
    },
];
